// iconos.h - Iconos del menu (tenedor, reloj, Z, carita), 24x24, solo tinta negra
#pragma once
#include <Arduino.h>

// . = transparente, X = tinta negra (se puede recolorear en el codigo)
const char* const ICONO_COMIDA[24] = {
  "........................",
  ".........XX...........X.",
  "XX...XX..XX.........XXX.",
  "XX...XX..XX........XXXXX",
  "XX...XX..XX.......XXXXXX",
  "XX...XX..XX.......XXXXXX",
  "XX...XX..XX.......XXXXXX",
  "XX...XX..XX.......XXXXXX",
  "XX...XX..XX.......XXXXXX",
  "XXX..XX.XXX.......XXXXXX",
  "XXXX.XXXXXX.......XXXXXX",
  ".XXXXXXXXX........XXXXXX",
  "...XXXXXX..........XXXXX",
  "...XXXXX............XXXX",
  "...XXXX..............XXX",
  "...XXXX..............XXX",
  "...XXXX..............XXX",
  "...XXXX..............XXX",
  "...XXXX..............XXX",
  "...XXXX..............XXX",
  "....XXX..............XXX",
  "....XXX..............XXX",
  "....XXX.................",
  "........................",
};

// . = transparente, X = tinta negra (se puede recolorear en el codigo)
const char* const ICONO_INFO[24] = {
  ".........XXXXXX.........",
  ".......XXXXXXXXXX.......",
  ".....XXXXXXXXXXXXXX.....",
  "....XXXXXXXXXXXXXXXX....",
  "...XXXXXXXXXXXXXXXXXX...",
  "..XXXXXX..XX.XX..XXXXX..",
  "..XXXXXX..XX.XX..XXXXX..",
  ".XXXXXXXXXXX.XXXXXXXXXX.",
  ".XXXX..XXXXX.XXXXXXXXXX.",
  "XXXXX..XXXXX.XXXXXX..XXX",
  "XXXXXXXXXXXX.XXXXXX..XXX",
  "XXXXXXXXXXXX.XXXXXXXXXXX",
  "XXXXXXXXXX.....XXXXXXXXX",
  "XXXXXXXXXX.....XXXXXXXXX",
  "XXXXXXXXXX.....XXXXXXXXX",
  ".XXXXXXXXX.....XXXXXXXX.",
  ".XXXXXXXXXXXXXXXXXXXXXX.",
  "..XXXXXXXXXXXXXXXXXXXX..",
  "..XXXXXXXXXXXXXXXXXXXX..",
  "...XXXXXXXXXXXXXXXXXX...",
  "....XXXXXXXXXXXXXXXX....",
  ".....XXXXXXXXXXXXXX.....",
  ".......XXXXXXXXXX.......",
  ".........XXXXXX.........",
};

// . = transparente, X = tinta negra (se puede recolorear en el codigo)
const char* const ICONO_DORMIR[24] = {
  "........................",
  "XXXXXXXXXXXXXXXXXXXX....",
  ".XXXXXXXXXXXXXXXXXXX....",
  ".XXXXXXXXXXXXXXXXXXX....",
  "..........XXXXXXXXXX....",
  "................XXXX....",
  "................XXXX....",
  "...............XXXX.....",
  "..............XXXX......",
  ".............XXXXX......",
  "...........XXXXXXX......",
  "...XXXXXXXXXXXXXXXXXXXX.",
  "...XXXXXXXXXXXXXXXXXXXX.",
  "...........XXXXX........",
  "..........XXXXX.........",
  ".........XXXXXX.........",
  "........XXXXXX..........",
  ".......XXXXXX...........",
  ".....XXXXXXX............",
  "....XXXXXXX.............",
  "..XXXXXXXXXXXXXXXXXXXXXX",
  ".XXXXXXXXXXXXXXXXXXXXXXX",
  ".XXXXXXXXXXXXXXXXXXXXXXX",
  "........................",
};

// . = transparente, X = tinta negra (se puede recolorear en el codigo)
const char* const ICONO_JUGAR[24] = {
  "........................",
  "................X.......",
  ".....XXX.......XXX......",
  ".....XXX.......XXX......",
  ".....XXX.......XXX......",
  ".....XXX.......XXX......",
  "......XX.......XXX......",
  "......XX.......XXX......",
  "......XX.......XXX......",
  "......XX.......X.X......",
  "......XX.......X.X......",
  "...............XXX......",
  "X......................X",
  "X.....................XX",
  "XX....................X.",
  ".XX..................XX.",
  ".XXX................XX..",
  "..XX................XX..",
  "..XXXX.............XXX..",
  "....XXXX..........XX....",
  "......XXXXXX....XXXX....",
  "........XXXXXXXXXXX.....",
  "........................",
  "........................",
};